name: furniture_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  google_sign_in: ^5.4.2
  cached_network_image: ^3.3.1

  # flutter
  flutter_redux: ^0.10.0
  cupertino_icons: ^1.0.5
  firebase_storage: ^11.0.4
  neon: ^0.1.0
  matrix4_transform: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  sleek_circular_slider: ^2.0.1

  # dart
  http: ^0.13.5
  redux: ^5.0.0
  built_value: ^8.4.1
  built_collection: ^5.1.1
  freezed_annotation: ^2.2.0
  convert: ^3.1.0
  redux_epics: ^0.15.1
  meta: ^1.7.0
  flutter_svg: ^0.22.0
  get: ^4.6.5
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  syncfusion_flutter_gauges: ^20.3.58
  #flutter_circular_slider: ^2.5.0
  carousel_slider: ^4.1.1
  model_viewer_plus: ^1.3.3
  zwidget: ^0.0.2
  lints: ^2.0.1
  cached_memory_image: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  built_value_generator: ^8.4.1
  freezed: any
  analyzer: any

dependency_overrides:
  rxdart: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/3d/
    - lib/products.json
